repos:
-   repo: git@github.com:Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '(docs\/_build|poetry.lock)'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --pattern, release/.*]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        additional_dependencies: ['click==8.0.4']
