"""
Demonstrating Proof of Possesssion (DPoP)-bound Task Token and Async Proxy for Nextflow Workflows.

This module provides client-side support for generating DPoP-bound task tokens
and running a local proxy for Nextflow pipelines.

Routes both TES and S3 traffic through DPoP.
"""

import contextlib
import os
from pathlib import Path
import subprocess
import tempfile
from typing import List, Optional

from cdislogging import get_logger

from gen3.auth import Gen3Auth
from gen3.dpop import dpop_proxy_context, resolve_service_endpoints

logging = get_logger(__name__)

# Written to a temp file and passed to `nextflow run` with `-c` last on every run.
# Nextflow merges a `-c` file over the config the pipeline already has rather than
# replacing it, and the last `-c` wins, so this redirects a config that points
# straight at a commons to the local proxy instead, one key at a time. It sets only
# the keys the proxy forces; workDir, region, executor and plugins stay the user's.
#
# The token is read from the environment rather than written here: a task token is
# a bearer-equivalent credential, and a temp file holding one is readable by every
# process on the host for the life of the run.
_PROXY_CONFIG_TEMPLATE = """\
// Generated by `gen3 nextflow run` - recreated every run, deleted when it ends.
//
// This overrides only what the DPoP proxy requires. Your own config still owns
// everything else: plugins, executor, container, region, workDir.
//
// The endpoints below are the local proxy, which signs every request with a
// short-lived key held only in memory and forwards it to your commons:
//
//     TES  {tes_endpoint}
//     S3   {s3_endpoint}
//
// To wire this up by hand instead, pass --no-generated-config; see the docs.
tes {{
    endpoint = 'http://127.0.0.1:{port}/ga4gh/tes'
    oauthToken = env('GEN3_DPOP_BOUND_TASK_TOKEN')
}}
aws {{
    // Gen3's S3 endpoint reads the token out of the SigV4 `Credential` field, so
    // the task token is the access key and the secret is never used.
    accessKey = env('GEN3_DPOP_BOUND_TASK_TOKEN')
    secretKey = 'N/A'
    client {{
        endpoint = 'http://127.0.0.1:{port}/s3'
        // Gen3's S3 endpoint reads the bucket name from the first segment of
        // the request path. Virtual-host addressing puts it in `Host` instead,
        // which the proxy has to overwrite, leaving the endpoint to read a key
        // prefix as the bucket name and refuse the request.
        s3PathStyleAccess = true
    }}
}}
"""


def run_gen3_nextflow(
    nf_args: List[str],
    auth: Gen3Auth,
    task_token_type: str = "WORKFLOW",
    task_token_expiration: Optional[int] = None,
    tes_endpoint: Optional[str] = None,
    s3_endpoint: Optional[str] = None,
    port: Optional[int] = None,
    generate_config: bool = True,
) -> int:
    """
    Wrap Nextflow execution with DPoP-bound task token security.

    Generates an ephemeral key, exchanges the user's credentials for a DPoP-bound
    task token, starts a local proxy, then runs Nextflow with the task token and
    proxy port in its environment as `GEN3_DPOP_BOUND_TASK_TOKEN` and
    `GEN3_DPOP_PROXY_PORT`.

    By default it also writes a temporary Nextflow config that redirects TES and S3
    to the proxy and passes it with `-c` last, so a config pointing straight at a
    commons runs through the proxy without being edited. Nextflow merges `-c` files
    over the existing config, so only the keys the proxy forces change - workDir,
    region, executor and plugins stay as the pipeline set them. Pass
    `generate_config=False` to point the config at the proxy by hand instead; see
    docs/nextflow.md.

    Args:
        nf_args (List[str]): Arguments to pass to `nextflow run`.
        auth (Gen3Auth): Authenticated Gen3Auth instance with endpoint and credentials.
        task_token_type (str): Type of task token to request. Defaults to "WORKFLOW".
        task_token_expiration (Optional[int]): Expiration time in seconds for the
            task token. The service default is used if omitted.
        tes_endpoint (Optional[str]): GA4GH TES endpoint URL. Defaults to
            {endpoint}/ga4gh/tes.
        s3_endpoint (Optional[str]): S3 service endpoint URL. Defaults to
            {endpoint}/workflows/s3.
        port (Optional[int]): Port for the proxy, or None for an OS-assigned one.
        generate_config (bool): Whether to generate a Nextflow config pointing at
            the proxy and pass it with `-c`. Defaults to True.

    Returns:
        int: Nextflow process exit code.

    Raises:
        Gen3AuthError: If the DPoP-bound token exchange fails.
        ProxyStartupError: If the local proxy cannot be started.
        FileNotFoundError: If the `nextflow` executable is not on PATH.
    """
    # Resolved up front so the generated config can name the real upstreams in its
    # header comment, and so a bad --tes-endpoint fails before the token exchange.
    resolved_tes_endpoint, resolved_s3_endpoint = resolve_service_endpoints(
        auth, tes_endpoint, s3_endpoint
    )

    with dpop_proxy_context(
        auth=auth,
        task_token_type=task_token_type,
        task_token_expiration=task_token_expiration,
        tes_endpoint=tes_endpoint,
        s3_endpoint=s3_endpoint,
        port=port,
    ) as (task_token, proxy_port):
        env = os.environ.copy()
        env["GEN3_DPOP_BOUND_TASK_TOKEN"] = task_token
        env["GEN3_DPOP_PROXY_PORT"] = str(proxy_port)

        with contextlib.ExitStack() as stack:
            args = list(nf_args)
            if generate_config:
                # The config outlives nothing: the directory goes away with the run.
                directory = stack.enter_context(tempfile.TemporaryDirectory())
                config_path = _write_proxy_config(
                    directory=directory,
                    proxy_port=proxy_port,
                    tes_endpoint=resolved_tes_endpoint,
                    s3_endpoint=resolved_s3_endpoint,
                )
                args += ["-c", config_path]
                logging.info(f"Generated Nextflow config: {config_path}")

            logging.info("*** Starting Nextflow run... ***")
            try:
                result = subprocess.run(
                    ["nextflow", "run"] + args, env=env, check=False
                )
            except FileNotFoundError:
                logging.error(
                    "Could not find `nextflow` on your PATH. Install it and try again."
                )
                raise
            logging.info("*** Completed Nextflow run! ***")
            return result.returncode


def _write_proxy_config(
    directory: str,
    proxy_port: int,
    tes_endpoint: str,
    s3_endpoint: str,
) -> str:
    """
    Write the Nextflow config that redirects TES and S3 to the local proxy.

    Args:
        directory (str): Directory to write into; the caller owns its lifetime.
        proxy_port (int): Port the DPoP proxy is listening on.
        tes_endpoint (str): Upstream TES endpoint, for the comment header.
        s3_endpoint (str): Upstream S3 endpoint, for the comment header.

    Returns:
        str: Path to the config file that was written.
    """
    contents = _PROXY_CONFIG_TEMPLATE.format(
        port=proxy_port,
        tes_endpoint=tes_endpoint,
        s3_endpoint=s3_endpoint,
    )

    path = Path(directory) / "gen3-dpop.config"
    path.write_text(contents)
    logging.debug(f"Generated Nextflow config {path}:\n{contents}")
    return str(path)
