# push will run on every pushed commit to any branch (so this will rerun the tests
# once a branch gets merged to main in addition to any new commits on any branch)
on: push

name: Build

jobs:
  pypi:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip --version
          pip install poetry
          pip -m poetry --version
      - name: Install dependencies
        run: |
          pip -m poetry install -vv --all-extras --no-interaction --no-cache
          pip -m poetry show -vv
        shell: bash
      - name: Build using pyinstaller
        run: |
          pip install pyinstaller==6.6.0
          pyinstaller --name gen3 --hidden-import gen3users --onefile ./gen3/cli/__main__.py 
      - name: Test build
        run: |
          cd ./dist
          gen3 --help




